version: "3.8"
services:
  mysql:
    image: agray998/animal-noise-db:latest
    build: ./db
    volumes:
      - type: volume
        source: animal-vol
        target: /var/lib/mysql
    networks:
      - "animal-net"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: animal_db
  front-end:
    image: agray998/animal-noise-front:latest
    build: ./front-end
    networks:
      - "animal-net"
    depends_on:
      - "mysql"
      - "animal-api"
      - "noise-api"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  animal-api:
    image: agray998/animal-noise-animal:latest
    build: ./animal-api
    networks:
      - "animal-net"
  noise-api:
    image: agray998/animal-noise-noise:latest
    build: ./noise-api
    networks:
      - "animal-net"
  nginx:
    image: nginx:latest
    ports:
      - published: 80
        target: 80
        protocol: tcp
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - "animal-net"
    depends_on:
      - "front-end"
volumes:
  animal-vol:
networks:
  animal-net:
